name: Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "25 * * * *"
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2                                                               
      - name: Set up Python 3.12                               
        uses: actions/setup-python@master                               
        with:                                 
          python-version: '3.12'
          cache: 'pip'

      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
  
      - name: Install dependencies
        run: |
          pip install -r python/requirements.txt

      - name: 🍳 Scrape top stories
        run: python3 python/dashfetcher.py
        
      - name: 🚀 Commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
